/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreatedEvent = IDL.Record({
  'id' : IDL.Text,
  'htmlLink' : IDL.Text,
});
export const CreateEventResult = IDL.Variant({
  'auth_expired' : IDL.Null,
  'error' : IDL.Text,
  'success' : CreatedEvent,
  'not_connected' : IDL.Null,
});
export const ExchangeResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});
export const ConnectionStatus = IDL.Variant({
  'disconnected' : IDL.Null,
  'connected' : IDL.Null,
});
export const RefreshResult = IDL.Variant({
  'no_refresh_token' : IDL.Null,
  'error' : IDL.Text,
  'success' : IDL.Text,
  'not_connected' : IDL.Null,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__tokenStore' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'create_event' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [CreateEventResult],
      [],
    ),
  'disconnect' : IDL.Func([], [], []),
  'exchange_auth_code' : IDL.Func([IDL.Text], [ExchangeResult], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'get_connection_status' : IDL.Func([], [ConnectionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refresh_access_token' : IDL.Func([], [RefreshResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreatedEvent = IDL.Record({ 'id' : IDL.Text, 'htmlLink' : IDL.Text });
  const CreateEventResult = IDL.Variant({
    'auth_expired' : IDL.Null,
    'error' : IDL.Text,
    'success' : CreatedEvent,
    'not_connected' : IDL.Null,
  });
  const ExchangeResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Null,
  });
  const ConnectionStatus = IDL.Variant({
    'disconnected' : IDL.Null,
    'connected' : IDL.Null,
  });
  const RefreshResult = IDL.Variant({
    'no_refresh_token' : IDL.Null,
    'error' : IDL.Text,
    'success' : IDL.Text,
    'not_connected' : IDL.Null,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__tokenStore' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'create_event' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [CreateEventResult],
        [],
      ),
    'disconnect' : IDL.Func([], [], []),
    'exchange_auth_code' : IDL.Func([IDL.Text], [ExchangeResult], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'get_connection_status' : IDL.Func([], [ConnectionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refresh_access_token' : IDL.Func([], [RefreshResult], []),
  });
};

export const init = ({ IDL }) => { return []; };