/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConnectionStatus = { 'disconnected' : null } |
  { 'connected' : null };
export type CreateEventResult = { 'auth_expired' : null } |
  { 'error' : string } |
  { 'success' : CreatedEvent } |
  { 'not_connected' : null };
export interface CreatedEvent { 'id' : string, 'htmlLink' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExchangeResult = { 'error' : string } |
  { 'success' : null };
export type RefreshResult = { 'no_refresh_token' : null } |
  { 'error' : string } |
  { 'success' : string } |
  { 'not_connected' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__tokenStore' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'create_event' : ActorMethod<[string, string, string], CreateEventResult>,
  'disconnect' : ActorMethod<[], undefined>,
  'exchange_auth_code' : ActorMethod<[string], ExchangeResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'get_connection_status' : ActorMethod<[], ConnectionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refresh_access_token' : ActorMethod<[], RefreshResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];